using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Web.UI;
using FreeTextBoxControls;


[assembly: AssemblyDescription("The no. 1 free ASP.NET HTML editor control for IE, Firefox, Opera, Safari, and Chrome.")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Refresh Development, Inc.")]
[assembly: AssemblyProduct("")]
[assembly: AssemblyCopyright("2005-2010")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: CLSCompliant(true)]
//
// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Revision and Build Numbers 
// by using the '*' as shown below:

[assembly: AssemblyVersion("3.3.1.*")]


// Web Resources for ASP.NET 1.x 
[assembly: WebResource("FreeTextBoxControls.Resources.JavaScript.FTB-FreeTextBox.js", "text/javascript")]
[assembly: WebResource("FreeTextBoxControls.Resources.JavaScript.FTB-ToolbarItems.js", "text/javascript")]
[assembly: WebResource("FreeTextBoxControls.Resources.JavaScript.FTB-Utility.js", "text/javascript")]
[assembly: WebResource("FreeTextBoxControls.Resources.JavaScript.FTB-Pro.js", "text/javascript")]
[assembly: WebResource("FreeTextBoxControls.Resources.JavaScript.FTB-ImageGallery.js", "text/javascript")]

// Utility Images
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Utility.folder.up.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Utility.folder.big.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Utility.folder.small.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Utility.image.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Utility.spacer.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Utility.locked.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Utility.unlocked.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Utility.restore.gif", "image/gif")]

// Office2003 Images 
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.buttons.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.bold.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.bulletedlist.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.copy.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.createlink.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.csharp.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.cut.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.delete.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.deletetablecolumn.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.deletetablerow.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.editstyle.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.edittable.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.edittablerow.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.edittablecell.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.editproperties.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.fontbackcolorpicker.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.fontforecolorpicker.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.iespellcheck.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.indent.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.insertdate.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.insertimage.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.insertimagefromgallery.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.insertrule.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.inserttable.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.inserttablecolumn.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.inserttablecolumnafter.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.inserttablecolumnbefore.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.inserttablerow.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.inserttablerowafter.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.inserttablerowbefore.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.inserttime.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.italic.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.justifycenter.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.justifyfull.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.justifyleft.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.justifyright.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.mergecells.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.mergecolumns.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.mergerows.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.mode.design.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.mode.html.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.netspell.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.numberedlist.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.outdent.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.paste.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.preview.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.print.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.redo.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.removeformat.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.save.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.separator.horizontal.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.separator.vertical.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.spellcheck.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.strikethrough.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.subscript.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.superscript.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.selectall.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.splitcells.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.toolbar.horizontal.background.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.toolbar.horizontal.end.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.toolbar.horizontal.start.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.toolbar.vertical.background.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.toolbar.vertical.end.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.toolbar.vertical.start.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.toolbarbuttoncss.off.out.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.toolbarbuttoncss.off.over.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.toolbarbuttoncss.on.out.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.toolbarbuttoncss.on.over.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.underline.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.undo.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.unlink.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.wordclean.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.wordcount.gif", "image/gif")]

[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.insertbutton.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.insertcheckbox.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.insertdropdownlist.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.insertform.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.insertlistbox.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.insertradiobutton.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.inserttextarea.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.inserttextbox.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.insertdiv.gif", "image/gif")]

// OfficeXP Images 
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.buttons.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.bold.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.bulletedlist.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.copy.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.createlink.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.csharp.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.cut.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.delete.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.deletetablecolumn.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.deletetablerow.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.editstyle.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.edittable.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.edittablerow.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.edittablecell.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.editproperties.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.fontbackcolorpicker.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.fontforecolorpicker.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.iespellcheck.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.indent.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.insertdate.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.insertimage.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.insertimagefromgallery.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.insertrule.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.inserttable.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.inserttablecolumn.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.inserttablecolumnafter.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.inserttablecolumnbefore.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.inserttablerow.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.inserttablerowafter.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.inserttablerowbefore.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.inserttime.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.italic.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.justifycenter.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.justifyfull.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.justifyleft.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.justifyright.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.mergecells.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.mergecolumns.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.mergerows.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.mode.design.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.mode.html.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.netspell.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.numberedlist.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.outdent.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.paste.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.preview.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.print.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.redo.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.removeformat.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.save.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.separator.horizontal.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.separator.vertical.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.spellcheck.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.strikethrough.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.subscript.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.superscript.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.selectall.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.splitcells.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.toolbar.horizontal.background.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.toolbar.horizontal.end.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.toolbar.horizontal.start.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.toolbar.vertical.background.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.toolbar.vertical.end.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.toolbar.vertical.start.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.toolbarbuttoncss.off.out.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.toolbarbuttoncss.off.over.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.toolbarbuttoncss.on.out.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.toolbarbuttoncss.on.over.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.underline.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.undo.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.unlink.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.wordclean.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.wordcount.gif", "image/gif")]

[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.insertbutton.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.insertcheckbox.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.insertdropdownlist.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.insertform.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.insertlistbox.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.insertradiobutton.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.inserttextarea.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.inserttextbox.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.insertdiv.gif", "image/gif")]


// Office2000 Images 
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.buttons.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.bold.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.bulletedlist.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.copy.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.createlink.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.csharp.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.cut.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.delete.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.deletetablecolumn.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.deletetablerow.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.editstyle.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.edittable.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.edittablerow.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.edittablecell.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.editproperties.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.fontbackcolorpicker.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.fontforecolorpicker.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.iespellcheck.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.indent.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.insertdate.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.insertimage.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.insertimagefromgallery.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.insertrule.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.inserttable.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.inserttablecolumn.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.inserttablecolumnafter.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.inserttablecolumnbefore.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.inserttablerow.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.inserttablerowafter.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.inserttablerowbefore.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.inserttime.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.italic.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.justifycenter.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.justifyfull.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.justifyleft.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.justifyright.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.mergecells.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.mergecolumns.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.mergerows.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.mode.design.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.mode.html.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.netspell.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.numberedlist.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.outdent.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.paste.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.preview.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.print.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.redo.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.removeformat.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.save.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.separator.horizontal.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.separator.vertical.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.spellcheck.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.strikethrough.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.subscript.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.superscript.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.selectall.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.splitcells.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.toolbar.horizontal.background.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.toolbar.horizontal.end.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.toolbar.horizontal.start.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.toolbar.vertical.background.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.toolbar.vertical.end.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.toolbar.vertical.start.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.toolbarbuttoncss.off.out.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.toolbarbuttoncss.off.over.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.toolbarbuttoncss.on.out.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.toolbarbuttoncss.on.over.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.underline.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.undo.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.unlink.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.wordclean.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.wordcount.gif", "image/gif")]

[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.insertbutton.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.insertcheckbox.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.insertdropdownlist.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.insertform.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.insertlistbox.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.insertradiobutton.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.inserttextarea.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.inserttextbox.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.insertdiv.gif", "image/gif")]

// OfficeMac Images 
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.buttons.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.bold.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.bulletedlist.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.copy.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.createlink.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.csharp.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.cut.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.delete.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.deletetablecolumn.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.deletetablerow.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.editstyle.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.edittable.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.edittablerow.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.edittablecell.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.editproperties.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.fontbackcolorpicker.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.fontforecolorpicker.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.iespellcheck.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.indent.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.insertdate.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.insertimage.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.insertimagefromgallery.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.insertrule.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.inserttable.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.inserttablecolumn.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.inserttablecolumnafter.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.inserttablecolumnbefore.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.inserttablerow.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.inserttablerowafter.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.inserttablerowbefore.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.inserttime.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.italic.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.justifycenter.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.justifyfull.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.justifyleft.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.justifyright.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.mergecells.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.mergecolumns.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.mergerows.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.mode.design.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.mode.html.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.netspell.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.numberedlist.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.outdent.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.paste.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.preview.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.print.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.redo.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.removeformat.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.save.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.separator.horizontal.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.separator.vertical.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.spellcheck.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.strikethrough.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.subscript.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.superscript.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.selectall.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.splitcells.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.toolbar.horizontal.background.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.toolbar.horizontal.end.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.toolbar.horizontal.start.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.toolbar.vertical.background.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.toolbar.vertical.end.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.toolbar.vertical.start.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.toolbarbuttoncss.off.out.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.toolbarbuttoncss.off.over.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.toolbarbuttoncss.on.out.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.toolbarbuttoncss.on.over.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.underline.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.undo.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.unlink.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.wordclean.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.wordcount.gif", "image/gif")]

[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.insertbutton.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.insertcheckbox.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.insertdropdownlist.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.insertform.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.insertlistbox.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.insertradiobutton.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.inserttextarea.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.inserttextbox.gif", "image/gif")]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.insertdiv.gif", "image/gif")]

//
// In order to sign your assembly you must specify a key to use. Refer to the 
// Microsoft .NET Framework documentation for more information on assembly signing.
//
// Use the attributes below to control which key is used for signing. 
//
// Notes: 
//   (*) If no key is specified, the assembly is not signed.
//   (*) KeyName refers to a key that has been installed in the Crypto Service
//       Provider (CSP) on your machine. KeyFile refers to a file which contains
//       a key.
//   (*) If the KeyFile and the KeyName values are both specified, the 
//       following processing occurs:
//       (1) If the KeyName can be found in the CSP, that key is used.
//       (2) If the KeyName does not exist and the KeyFile does exist, the key 
//           in the KeyFile is installed into the CSP and used.
//   (*) In order to create a KeyFile, you can use the sn.exe (Strong Name) utility.
//       When specifying the KeyFile, the location of the KeyFile should be
//       relative to the project output directory which is
//       %Project Directory%\obj\<configuration>. For example, if your KeyFile is
//       located in the project directory, you would specify the AssemblyKeyFile 
//       attribute as [assembly: AssemblyKeyFile("..\\..\\mykey.snk")]
//   (*) Delay Signing is an advanced option - see the Microsoft .NET Framework
//       documentation for more information on this.
//
[assembly: AssemblyDelaySign(false)]
[assembly: AssemblyKeyFile("..\\..\\FreeTextBox.snk")]
[assembly: AssemblyKeyName("")]
