using System.Reflection;
using System.Runtime.CompilerServices;
using FreeTextBoxControls;
using FreeTextBoxControls.Support;

//
// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
//
[assembly: AssemblyTitle("FreeTextBox 3.x | ASP.NET 1.0")]
[assembly: AssemblyDescription("The no. 1 free ASP.NET HTML editor control for IE and Mozilla.")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("")]
[assembly: AssemblyCopyright("2006")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]		

//
// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Revision and Build Numbers 
// by using the '*' as shown below:

[assembly: AssemblyVersion("3.2.3.*")]

// Web Resources for ASP.NET 1.x 
[assembly: WebResource("FreeTextBoxControls.Resources.JavaScript.FTB-FreeTextBox.js", ContentType.TextComponent)]
[assembly: WebResource("FreeTextBoxControls.Resources.JavaScript.FTB-ToolbarItems.js", ContentType.TextComponent)]
[assembly: WebResource("FreeTextBoxControls.Resources.JavaScript.FTB-Utility.js", ContentType.TextComponent)]
[assembly: WebResource("FreeTextBoxControls.Resources.JavaScript.FTB-Pro.js", ContentType.TextComponent)]
[assembly: WebResource("FreeTextBoxControls.Resources.JavaScript.FTB-ImageGallery.js", ContentType.TextComponent)]

// Utility Images
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Utility.folder.up.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Utility.folder.big.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Utility.folder.small.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Utility.image.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Utility.spacer.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Utility.locked.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Utility.unlocked.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Utility.restore.gif",ContentType.ImageGif)]

// Office2003 Images 
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.buttons.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.buttons.png",ContentType.ImagePng)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.bold.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.bulletedlist.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.copy.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.createlink.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.csharp.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.cut.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.delete.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.deletetablecolumn.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.deletetablerow.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.editstyle.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.edittable.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.edittablerow.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.edittablecell.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.editproperties.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.fontbackcolorpicker.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.fontforecolorpicker.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.iespellcheck.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.indent.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.insertdate.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.insertimage.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.insertimagefromgallery.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.insertrule.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.inserttable.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.inserttablecolumn.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.inserttablecolumnafter.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.inserttablecolumnbefore.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.inserttablerow.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.inserttablerowafter.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.inserttablerowbefore.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.inserttime.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.italic.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.justifycenter.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.justifyfull.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.justifyleft.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.justifyright.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.mergecells.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.mergecolumns.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.mergerows.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.mode.design.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.mode.html.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.netspell.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.numberedlist.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.outdent.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.paste.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.preview.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.print.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.redo.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.removeformat.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.save.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.separator.horizontal.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.separator.vertical.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.spellcheck.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.strikethrough.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.subscript.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.superscript.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.selectall.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.splitcells.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.toolbar.horizontal.background.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.toolbar.horizontal.end.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.toolbar.horizontal.start.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.toolbar.vertical.background.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.toolbar.vertical.end.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.toolbar.vertical.start.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.toolbarbuttoncss.off.out.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.toolbarbuttoncss.off.over.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.toolbarbuttoncss.on.out.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.toolbarbuttoncss.on.over.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.underline.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.undo.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.unlink.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.wordclean.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.wordcount.gif",ContentType.ImageGif)]

[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.insertbutton.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.insertcheckbox.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.insertdropdownlist.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.insertform.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.insertlistbox.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.insertradiobutton.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.inserttextarea.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.inserttextbox.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2003.insertdiv.gif",ContentType.ImageGif)]

// OfficeXP Images 
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.buttons.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.buttons.png",ContentType.ImagePng)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.bold.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.bulletedlist.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.copy.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.createlink.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.csharp.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.cut.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.delete.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.deletetablecolumn.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.deletetablerow.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.editstyle.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.edittable.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.edittablerow.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.edittablecell.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.editproperties.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.fontbackcolorpicker.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.fontforecolorpicker.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.iespellcheck.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.indent.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.insertdate.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.insertimage.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.insertimagefromgallery.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.insertrule.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.inserttable.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.inserttablecolumn.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.inserttablecolumnafter.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.inserttablecolumnbefore.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.inserttablerow.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.inserttablerowafter.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.inserttablerowbefore.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.inserttime.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.italic.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.justifycenter.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.justifyfull.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.justifyleft.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.justifyright.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.mergecells.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.mergecolumns.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.mergerows.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.mode.design.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.mode.html.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.netspell.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.numberedlist.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.outdent.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.paste.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.preview.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.print.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.redo.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.removeformat.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.save.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.separator.horizontal.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.separator.vertical.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.spellcheck.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.strikethrough.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.subscript.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.superscript.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.selectall.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.splitcells.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.toolbar.horizontal.background.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.toolbar.horizontal.end.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.toolbar.horizontal.start.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.toolbar.vertical.background.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.toolbar.vertical.end.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.toolbar.vertical.start.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.toolbarbuttoncss.off.out.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.toolbarbuttoncss.off.over.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.toolbarbuttoncss.on.out.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.toolbarbuttoncss.on.over.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.underline.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.undo.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.unlink.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.wordclean.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.wordcount.gif",ContentType.ImageGif)]

[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.insertbutton.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.insertcheckbox.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.insertdropdownlist.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.insertform.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.insertlistbox.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.insertradiobutton.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.inserttextarea.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.inserttextbox.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeXP.insertdiv.gif",ContentType.ImageGif)]


// Office2000 Images 
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.buttons.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.buttons.png",ContentType.ImagePng)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.bold.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.bulletedlist.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.copy.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.createlink.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.csharp.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.cut.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.delete.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.deletetablecolumn.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.deletetablerow.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.editstyle.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.edittable.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.edittablerow.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.edittablecell.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.editproperties.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.fontbackcolorpicker.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.fontforecolorpicker.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.iespellcheck.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.indent.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.insertdate.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.insertimage.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.insertimagefromgallery.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.insertrule.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.inserttable.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.inserttablecolumn.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.inserttablecolumnafter.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.inserttablecolumnbefore.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.inserttablerow.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.inserttablerowafter.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.inserttablerowbefore.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.inserttime.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.italic.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.justifycenter.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.justifyfull.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.justifyleft.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.justifyright.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.mergecells.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.mergecolumns.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.mergerows.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.mode.design.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.mode.html.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.netspell.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.numberedlist.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.outdent.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.paste.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.preview.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.print.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.redo.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.removeformat.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.save.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.separator.horizontal.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.separator.vertical.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.spellcheck.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.strikethrough.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.subscript.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.superscript.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.selectall.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.splitcells.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.toolbar.horizontal.background.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.toolbar.horizontal.end.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.toolbar.horizontal.start.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.toolbar.vertical.background.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.toolbar.vertical.end.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.toolbar.vertical.start.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.toolbarbuttoncss.off.out.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.toolbarbuttoncss.off.over.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.toolbarbuttoncss.on.out.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.toolbarbuttoncss.on.over.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.underline.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.undo.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.unlink.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.wordclean.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.wordcount.gif",ContentType.ImageGif)]

[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.insertbutton.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.insertcheckbox.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.insertdropdownlist.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.insertform.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.insertlistbox.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.insertradiobutton.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.inserttextarea.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.inserttextbox.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.Office2000.insertdiv.gif",ContentType.ImageGif)]

// OfficeMac Images 
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.buttons.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.buttons.png",ContentType.ImagePng)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.bold.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.bulletedlist.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.copy.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.createlink.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.csharp.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.cut.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.delete.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.deletetablecolumn.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.deletetablerow.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.editstyle.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.edittable.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.edittablerow.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.edittablecell.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.editproperties.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.fontbackcolorpicker.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.fontforecolorpicker.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.iespellcheck.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.indent.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.insertdate.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.insertimage.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.insertimagefromgallery.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.insertrule.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.inserttable.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.inserttablecolumn.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.inserttablecolumnafter.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.inserttablecolumnbefore.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.inserttablerow.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.inserttablerowafter.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.inserttablerowbefore.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.inserttime.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.italic.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.justifycenter.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.justifyfull.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.justifyleft.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.justifyright.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.mergecells.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.mergecolumns.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.mergerows.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.mode.design.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.mode.html.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.netspell.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.numberedlist.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.outdent.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.paste.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.preview.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.print.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.redo.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.removeformat.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.save.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.separator.horizontal.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.separator.vertical.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.spellcheck.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.strikethrough.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.subscript.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.superscript.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.selectall.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.splitcells.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.toolbar.horizontal.background.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.toolbar.horizontal.end.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.toolbar.horizontal.start.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.toolbar.vertical.background.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.toolbar.vertical.end.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.toolbar.vertical.start.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.toolbarbuttoncss.off.out.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.toolbarbuttoncss.off.over.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.toolbarbuttoncss.on.out.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.toolbarbuttoncss.on.over.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.underline.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.undo.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.unlink.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.wordclean.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.wordcount.gif",ContentType.ImageGif)]

[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.insertbutton.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.insertcheckbox.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.insertdropdownlist.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.insertform.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.insertlistbox.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.insertradiobutton.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.inserttextarea.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.inserttextbox.gif",ContentType.ImageGif)]
[assembly: WebResource("FreeTextBoxControls.Resources.Images.OfficeMac.insertdiv.gif",ContentType.ImageGif)]

//
// In order to sign your assembly you must specify a key to use. Refer to the 
// Microsoft .NET Framework documentation for more information on assembly signing.
//
// Use the attributes below to control which key is used for signing. 
//
// Notes: 
//   (*) If no key is specified, the assembly is not signed.
//   (*) KeyName refers to a key that has been installed in the Crypto Service
//       Provider (CSP) on your machine. KeyFile refers to a file which contains
//       a key.
//   (*) If the KeyFile and the KeyName values are both specified, the 
//       following processing occurs:
//       (1) If the KeyName can be found in the CSP, that key is used.
//       (2) If the KeyName does not exist and the KeyFile does exist, the key 
//           in the KeyFile is installed into the CSP and used.
//   (*) In order to create a KeyFile, you can use the sn.exe (Strong Name) utility.
//       When specifying the KeyFile, the location of the KeyFile should be
//       relative to the project output directory which is
//       %Project Directory%\obj\<configuration>. For example, if your KeyFile is
//       located in the project directory, you would specify the AssemblyKeyFile 
//       attribute as [assembly: AssemblyKeyFile("..\\..\\mykey.snk")]
//   (*) Delay Signing is an advanced option - see the Microsoft .NET Framework
//       documentation for more information on this.
//
[assembly: AssemblyDelaySign(false)]
[assembly: AssemblyKeyFile("FreeTextBox.snk")]
[assembly: AssemblyKeyName("")]
